name: Balea Nightly Build
on:
  schedule:
    - cron:  '0 6 * * *'
jobs:
  build:
    env:
      BUILD_CONFIG: Release
    name: Build
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: microsoft/mssql-server-linux
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
        - 5433:1433
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
    - name: dotnet build
      run: dotnet build Balea.sln -c $BUILD_CONFIG
    - name: dotnet test [FunctionalTests]
      run: dotnet test ./test/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
    - name: dotnet pack [Balea]
      run: dotnet pack ./src/Balea/Balea.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix ${{ join('-preview', $GITHUB_RUN_ID) }} --no-build --include-source --include-symbols
    - name: dotnet pack [Balea.Configuration.Store]
      run: dotnet pack ./src/Balea.Configuration.Store/Balea.Configuration.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix ${{ join('-preview', $GITHUB_RUN_ID) }} --no-build --include-source --include-symbols
    - name: dotnet pack [Balea.EntityFrameworkCore.Store]
      run: dotnet pack ./src/Balea.EntityFrameworkCore.Store/Balea.EntityFrameworkCore.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix ${{ join('-preview', $GITHUB_RUN_ID) }} --no-build --include-source --include-symbols
    - name: Publish nuget
      run: |
          for f in ./artifacts/*.nupkg
          do
            curl --silent --show-error --fail -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
            if [ $? -eq 0 ]
            then
              echo "successfully pushed $f"
            else
              echo "failed to push $f" >&2
              exit 1
            fi
          done
      shell: bash
